### ISSUE TITLE
ImportError： TypeError: __init__() got multiple values for argument 'sio'

### ISSUE THREAD

**Issue by Cat-L** [nonebot/nonebot-test#14]
03-05 22:07:27 [ERROR] nonebot | Failed to import "nonebot_plugin_test"
Traceback (most recent call last):
  File "d:\work\environment\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\work\environment\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Work\Environment\Python\Scripts\nb.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "d:\work\environment\python\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "d:\work\environment\python\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "d:\work\environment\python\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\work\environment\python\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\work\environment\python\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "d:\work\environment\python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "d:\work\environment\python\lib\site-packages\nb_cli\handlers\deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "d:\work\environment\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "d:\work\environment\python\lib\site-packages\nonebot\plugin\load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "d:\work\environment\python\lib\site-packages\nonebot\plugin\load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "d:\work\environment\python\lib\site-packages\nonebot\plugin\manager.py", line 129, in load_all_plugins
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
  File "d:\work\environment\python\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "d:\work\environment\python\lib\site-packages\nonebot\plugin\manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "d:\work\environment\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\work\environment\python\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\work\environment\python\lib\site-packages\nonebot_plugin_test\__init__.py", line 44, in <module>
    websocket = WebSocket("1.1", "ws", TEST_WS_PATH, sio=sio)
TypeError: __init__() got multiple values for argument 'sio'

版本：
python：3.7.12
nonebot:2.0.0b2
nonebot-plugin-test:0.3.0
os:windows10 1909

请问是怎么回事呀？

**Comment by yanyongyu** [comment]
beta版本不支持test插件哦，beta目前使用nonebug作为单测解决方案
